name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory out

    - name: Configure
      working-directory: out
      run: |
        cmake -DNO_CLANG_FORMAT=1 -DCMAKE_BUILD_TYPE=Release -A x64 ../build

    - name: Build
      working-directory: out
      run: |
        $threads = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
        cmake --build . --config Release --parallel $threads

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: icebox-master-win64
        path: bin
